- name: functions
  hosts: local
  connection: local
  vars:
    technologies: DevOps, ansible, linux, shell
  # dictionary == map
    tags:
      application: Rohith
      domain: aws
  tasks:
  - name: print functions
    ansible.builtin.debug:
      msg: "name is {{ name | default('Rohith') }}"
  
  - name: spilt
    ansible.builtin.debug:
      msg: "List is {{ technologies | split(',') }}"

  - name: convert map to List
    ansible.builtin.debug:
      msg: "Map list is {{ tags |  dict2items }}"

